### PR TITLE
iss-hipcms-611: Basic CQRS + Event Sourcing implementation

### PR DESCRIPTION
**Pull request by SvenEV**
What the Data Store service currently does:
* It uses a (locally-hosted) EventStore instance as the event log
* Using the sample POST method in ExhibitsController, events can be created and stored
* The CacheDatabaseManager registers itself as a subscriber for events so that it can maintain a (locally-hosted) MongoDB database holding the current state of everything
* Using the sample GET method in ExhibitsController, all stored exhibits can be retrieved

How to test (see README):
* Download & run a EventStore instance on localhost
* Download & run a MongoDB instance on localhost
* Run HiP-DataStore

Let me know if there are any questions or problems.
Please provide feedback whether the implementation roughly meets our requirements and your expectations.

### CODE REVIEW

**Review by objectliteral — APPROVED** [review]
I wanted to leave some comments but I don't know how to leave annotations on specific parts of the code so screw it.

**Comment by janis-kra** [comment]
@objectliteral FYI: to do that, click "Files changed" just above the initial PR comment by the author and in the displayed source code click the "+" sign that appear when you hover over a line of code.

Reviewing this now.

**Comment by janis-kra** [comment]
Functionality is as expected.

didn't look at the code though because @objectliteral has a better understanding of how the architecture should look etc., so maybe you can add your remarks and then merge and / or request changes

**Review by janis-kra — APPROVED** [review]

**Comment by SvenEV** [comment]
Hey, thanks for reviewing, but I think @objectliteral created the "develop" branch and already merged the changes of this PR into it - at least all my changes are there and I have continued my work based on the develop branch.

**Comment by SvenEV** [comment]
So maybe we should just close this PR?

**Comment by janis-kra** [comment]
oh, okay -- closing this then. I just configured the repository s.t. you can only push to develop/master with a PR in the future

**Pull request closed without merging**
