### PR TITLE
migrating to ASP.NET Core 2.1

### PR DESCRIPTION
**Pull request by danywehbe**

### CODE REVIEW

**Comment by danywehbe** [comment]
The build will keep failing until we change the configurations at "HiP-ServiceConfig"

**Comment by thielep** [comment]
The changes that have to be made at "HiP-ServiceConfig" should only affect the release of the DataStore, but not the build. The build should succeed regardless. The logs of the build on the TFS say that there are still errors in "ExhibitsTest.cs" of the "HiP-DataStore.Tests" project. With them fixed I think the build should be successful.

**Comment by danywehbe** [comment]
The problem that it worked just fine on my computer! what do you think is the problem?

**Comment by thielep** [comment]
Did you check the "ExhibitTests.cs" file I mentionend? There were actually errors in there. I was also able to run it in VS but when I tried to built it manually it failed, just like on the TFS.

**Review by thielep — APPROVED** [review]
Looks good to me. But remember to also upgrade the dotnet image used in the Dockerfile of "HiP-ServiceConfig/DataStore-develop" before merging this PR.

**Pull request merged**
